platform :ios, '8.0'
use_frameworks!

target 'TuTurno' do
  pod 'SwiftyJSON', '~> 2.3.2'
  pod 'Alamofire', '~> 3.0.1'
  pod 'ObjectMapper', '~> 1.0.1'
  pod 'Kingfisher', '~> 2.0.4'
  pod 'SwiftLocation', '~> 0.9.0' 
  pod 'RealmSwift', '~> 0.98'
  pod 'DateTools','~> 1.7'
  pod 'FBSDKLoginKit', '~> 4.13'
end
